export const data = [
	{
		id: 1,
		img: '/images/productos/img1.jpg',
		nameProduct: 'Sombrero Fieltro de Lana ',
		price: 300,
		quantity: 1,
	},
	{
		id: 2,
		img: '/images/productos/img2.jpg',
		nameProduct: 'Blusa Cuello Cadete en Seda Francesa',
		price: 200,
		quantity: 1,
	},
	{
		id: 3,
		img: '/images/productos/img3.jpg',
		nameProduct: 'Blusa Cuello Drapeado en Seda Francesa',
		price: 200,
		quantity: 1,
	},
	{
		id: 4,
		img: '/images/productos/img4.jpg',
		nameProduct: 'Blusa Cuello Cerrado en Seda Francesa',
		price: 200,
		quantity: 1,
	},
	{
		id: 5,
		img: '/images/productos/img5.jpg',
		nameProduct: 'Chaqueta con Manga Ranglan Acampanada en Lino',
		price: 300,
		quantity: 1,
	},
	{
		id: 6,
		img: '/images/productos/img6.jpg',
		nameProduct: 'Chaqueta Manga Ranglan Cuello Cadete en Lino',
		price: 300,
		quantity: 1,
	},
	{
		id: 7,
		img: '/images/productos/img7.jpg',
		nameProduct: 'Saco a la Cintura en Lino ',
		price: 300,
		quantity: 1,
	},
	{
		id: 8,
		img: '/images/productos/img8.jpg',
		nameProduct: 'Abrigo Cuello Cadete en Paño Chileno',
		price: 1500,
		quantity: 1,
	},
	{
		id: 9,
		img: '/images/productos/img9.jpg',
		nameProduct: 'Abrigo Largo Manga Ranglan en Paño Chileno ',
		price: 2000,
		quantity: 1,
	},
	{
		id: 10,
		img: '/images/productos/img10.jpg',
		nameProduct: 'Pantalón Bota Acampanada en Lino',
		price: 200,
		quantity: 1,
	},
	{
		id: 11,
		img: '/images/productos/img11.jpg',
		nameProduct: 'Pantalón Bota Recta en Lino',
		price: 200,
		quantity: 1,
	},
	{
		id: 12,
		img: '/images/productos/img12.jpg',
		nameProduct: 'Pantalón Palazo en Seda Francesa',
		price: 200,
		quantity: 1,
	},
	{
		id: 13,
		img: '/images/productos/img13.jpg',
		nameProduct: 'Chamarra Bomber en Cuerina',
		price: 300,
		quantity: 1,
	},
	{
		id: 14,
		img: '/images/productos/img14.jpg',
		nameProduct: 'Saco Solapa Corta de dos Botones Tela Casimir',
		price: 800,
		quantity: 1,
	},
	{
		id: 15,
		img: '/images/productos/img15.jpg',
		nameProduct: 'Camisa Tela Rojo a Rayas Modelo Clasico',
		price: 250,
		quantity: 1,
	},
	{
		id: 16,
		img: '/images/productos/img16.jpg',
		nameProduct: 'Vestido de Novia Corte Sirena Asimétrica con Velo Corto',
		price: 4000,
		quantity: 1,
	},
	
];